import "./(styles)/globals.css";
import type { Metadata } from "next";
import Body from "@/app/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Body>{children}</Body>
    </html>
  );
}
